### ISSUE TITLE
GetVersionEx(&info) error 

### ISSUE THREAD

**Issue by Souhardya** [alextspy/ghostlulz-botnet#1]
I am a little bit n00b to C just wanted to know what flags you are using while compiling the file .. ?

**Comment by Souhardya** [comment]
Can you point me out to the flags you used i cant get it to a stable compile actually .. it would be awesome if you help me

**Comment by ghostlulzhacks** [comment]
I actually haven't touched that code in like a year half so I forget the exact flags I used to compile and the flags vary depending on what compiler you are using. But if I recall correctly I had to link the dll to the c code. So depending on your compiler you will need to look up up the command to link dlls (its normally somthing like "-l NameOfDll"). If you need more help copy paste the exact error and send to me.

________________________________

**Comment by Souhardya** [comment]
Actually I compiled the program somehow like this  .\gcc.exe .\main.c  -Wimplicit-function-declaration -lws2_32  -o main.exe .. .but after executing the program crashes 

The instruction at 0x0040169c referenced memory at 0x000012 . memory couldnt be read

**Comment by Souhardya** [comment]
and also i see a drastic change in stub size mine is around 140 kb 64 BIT tho .. yours was like 90 kb :)

**Comment by ghostlulzhacks** [comment]
Not sure what the issue is only thing I see is that your using "gcc" so im going to assume your compiling  on linux. Maybe try to use windows to compile I know at the time I was using "cl.exe from visual studio" but alot of ppl use "mingw compiler". Other than that im not really sure... the code is shit so it could be that too lol

**Comment by Souhardya** [comment]
actually I am compiling on windows only :) tdm gcc compiler .. indeed thank you for your assistance tho i will try my best to get it running as of now its crashing like fuck
